from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from macos_state_explorer.core.snapshot import create_snapshot
from macos_state_explorer.exports.framework import (
    EvidenceBundleExport,
    EvidenceBundleExportRequest,
    EvidenceBundleRegistry,
    artifact_entry,
    prepare_export_output,
)
from macos_state_explorer.reports.local_network import build_local_network_report, write_local_network_support_bundle


@dataclass(frozen=True)
class LocalNetworkVendorFeedbackAppleProvider:
    branch_id: str = "manual-empty-trash-reboot"

    def export(self, request: EvidenceBundleExportRequest) -> EvidenceBundleExport:
        return export_local_network_vendor_feedback_for_apple(
            request.output,
            audience=request.audience,
            target=request.target,
            issue=request.issue,
            branch_id=self.branch_id,
        )


def register_local_network_exports(registry: EvidenceBundleRegistry) -> None:
    registry.register(
        audience="vendor-feedback",
        target="apple",
        issue="local-network",
        provider=LocalNetworkVendorFeedbackAppleProvider(),
    )


def export_local_network_vendor_feedback_for_apple(
    output: Path,
    *,
    audience: str = "vendor-feedback",
    target: str = "apple",
    issue: str = "local-network",
    branch_id: str = "manual-empty-trash-reboot",
) -> EvidenceBundleExport:
    output = prepare_export_output(output)
    support_bundle = output / "support-bundle"
    snapshot = create_snapshot(fast=True)
    report = build_local_network_report(snapshot, branch_id=branch_id)
    write_local_network_support_bundle(report, support_bundle, branch_id=branch_id)
    brief = _render_vendor_feedback_brief(
        audience=audience,
        target=target,
        issue=issue,
        support_bundle=support_bundle,
    )
    (output / "vendor-feedback.md").write_text(brief + "\n", encoding="utf-8")
    manifest = {
        "export_schema_version": 1,
        "audience": audience,
        "target": target,
        "issue": issue,
        "provider_id": "local-network.apple.vendor-feedback",
        "generated_by": "mse export evidence-bundle",
        "artifacts": _artifact_manifest(output),
        "framework": {
            "provider_model": "registry",
            "audiences": [audience],
            "targets": [target],
            "issues": [issue],
            "extension_note": (
                "Additional audiences, targets, and issue engines register providers "
                "without changing the export core."
            ),
        },
    }
    return EvidenceBundleExport(manifest=manifest, output=output)


def _artifact_manifest(output: Path) -> list[dict[str, str]]:
    known_descriptions = {
        "vendor-feedback.md": "Audience-specific vendor feedback summary.",
        "support-bundle/report.json": "Machine-readable Local Network diagnostic report.",
        "support-bundle/report.txt": "Human-readable Local Network diagnostic report.",
        "support-bundle/command.json": "Command and export metadata for the support bundle.",
        "support-bundle/environment.json": "Local environment summary for support context.",
    }
    entries: list[dict[str, str]] = []
    for path in sorted(
        item
        for item in output.rglob("*")
        if item.is_file() and item.relative_to(output).as_posix() != "manifest.json"
    ):
        relative = path.relative_to(output).as_posix()
        media_type = _media_type_for(path)
        entries.append(
            artifact_entry(
                relative,
                description=known_descriptions.get(relative, "Support evidence artifact."),
                media_type=media_type,
            )
        )
    return entries


def _media_type_for(path: Path) -> str:
    if path.suffix == ".json":
        return "application/json"
    if path.suffix in {".md", ".txt"}:
        return "text/plain"
    if path.suffix == ".plist":
        return "application/x-plist"
    return "application/octet-stream"


def _render_vendor_feedback_brief(
    *,
    audience: str,
    target: str,
    issue: str,
    support_bundle: Path,
) -> str:
    report_txt = support_bundle / "report.txt"
    report_hint = f"See {report_txt.relative_to(support_bundle.parent).as_posix()} for the full diagnostic report."
    lines: Sequence[str] = (
        "Evidence bundle export",
        "",
        f"Audience: {audience}",
        f"Target: {target}",
        f"Issue: {issue}",
        "",
        "This export is generated by the generic evidence export framework.",
        "The export core selects providers by audience, target, and issue; this initial provider packages Local Network evidence for vendor feedback.",
        "",
        "Included evidence",
        f"- {report_hint}",
        "- See support-bundle/report.json for machine-readable evidence.",
        "- See support-bundle/environment.json for local environment context.",
    )
    return "\n".join(lines)
